[project]
name = "ftk"
version = "0.1.0"
authors = [{ name = "tomas", email = "pg57742@uminho.pt" }]
description = ""
license = {text = "MIT"}
dependencies = ["jjcli"]

[project.scripts]
ftk-occ = "ftk.base:main"
